### PR TITLE
Empty files now behave similarly to absent files.

### LINKED ISSUE #34: Loading empty file causes parsing error
Imho, if a config file is provided, but empty, behaviour should be as if it were not present at all.
Therefore, I feel like if data is null or undefined, return an empty object rather than throwing ConfigurationError?

fs.readFileSync returns undefined on reading a file with empty contents.
yaml parser returns undefined, as contents is undefined.

on line 28, file.ts, !object, null(explicit) and isArray is checked. to throw the error.
I'm thinking perhaps, remove the null check and on the return, do something like:
```return data || {};```
That should catch nullish returns fairly gracefully?

### PR DESCRIPTION
**Pull request by stormwulfren**
Fixes #34

### CODE REVIEW

**Comment by codemariner** [comment]
Hi @reznyt . Thanks for update! Looks good but could you please add a test? If not, I can add one later.

**Comment by stormwulfren** [comment]
Would you mind doing it? I'm not too familiar with JS unit testing, and I'm kinda swamped until next week ...

**Comment by codemariner** [comment]
@reznyt 👍 - btw, I'm curious; how'd you come across the project and where are  you using it?

**Review by codemariner — APPROVED** [review]

**Comment by stormwulfren** [comment]
@codemariner Sorry, been away from code for a couple weeks! Yeah, I was running around looking for lightweight config managers. Others were just overkill for the purpose, had endless dependencies, not type safe, or just simply didn't do what I needed. I settled on tconf since it's fairly tiny and lets me resolve env vars with config files pretty seamlessly. It's not perfect, but it's something I didn't have to fight with to get to do what I needed.

I'm using it in what I think it's most easily described as IoT middleware software. Can't elaborate more until release ;)

**Pull request merged**
